// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDevicesIp(arg1, arg2) {
  return window['go']['main']['App']['GetDevicesIp'](arg1, arg2);
}

export function ReadHoldingRegisters(arg1, arg2) {
  return window['go']['main']['App']['ReadHoldingRegisters'](arg1, arg2);
}
